version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ADMIN_PASSWORD=admin123      # change this in production
      - SECRET_KEY=supersecretkey
    volumes:
      - .:/app
    restart: always

